spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:3521:XE
    username: username
    password: superSecretPasswordThatShouldNeverBeInPlainTextInVCS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect